---
- hosts: webservers
  vars:
  - warName: java-example.war
  - warRemotePath: /opt/apache-tomcat-8.5.53/webapps

  tasks:
  - name: Copy WAR to server
    copy: src=target/java-example.war dest={{ warRemotePath }}/{{ warName }}
